export const START_LOADING = 'START_LOADING';
export const END_LOADING = 'END_LOADING';

export const SET_ERROR = 'SET_ERROR';

export const GET_PLAYLISTS = 'GET_PLAYLISTS';
export const GET_PLAYLIST_TRACKS = 'GET_PLAYLIST_TRACKS';
export const GET_TRACK_DETAILS = 'GET_TRACK_DETAILS';
